apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-consumer-secret
data:
  RabbitMqHost: YW1xcDovL3VzZXI6UEFTU1dPUkRAcmFiYml0bXEucmFiYml0LnN2Yy5jbHVzdGVyLmxvY2FsOjU2NzI=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-consumer
  namespace: default
  labels:
    app: rabbitmq-consumer
spec:
  selector:
    matchLabels:
      app: rabbitmq-consumer
  template:
    metadata:
      labels:
        app: rabbitmq-consumer
    spec:
      containers:
        - name: rabbitmq-consumer
          image: eu.gcr.io/twy-website-analytics/rabbitmq-consumer:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-trigger-app
  namespace: default
  labels:
    app: rabbitmq-trigger-app
spec:
  selector:
    matchLabels:
      app: rabbitmq-trigger-app
  template:
    metadata:
      labels:
        app: rabbitmq-trigger-app
    spec:
      containers:
        - name: rabbitmq-trigger-app
          image: eu.gcr.io/twy-website-analytics/rabbitmq-trigger-app:latest
          imagePullPolicy: Always
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: rabbitmq-consumer
  namespace: default
spec:
  scaleTargetRef:
    name: rabbitmq-consumer
  pollingInterval: 5 # Optional. Default: 30 seconds
  cooldownPeriod: 30 # Optional. Default: 300 seconds
  minReplicaCount: 1 # Optional. Default: 100
  maxReplicaCount: 50 # Optional. Default: 100
  triggers:
    - type: rabbitmq
      metadata:
        queueName: create-erc-725-profile
        queueLength: "5"
      authenticationRef:
        name: rabbitmq-consumer-trigger
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: rabbitmq-consumer-trigger
  namespace: default
spec:
  secretTargetRef:
    - parameter: host
      name: rabbitmq-consumer-secret
      key: RabbitMqHost
---

