apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "relayer.fullname" . }}
spec:
  scaleTargetRef:
    name: {{ include "relayer.fullname" . }}
    kind: StatefulSet
  pollingInterval: 5 # Optional. Default: 30 seconds
  cooldownPeriod: 30 # Optional. Default: 300 seconds
  minReplicaCount: 2 # Optional. Default: 100
  maxReplicaCount: 50 # Optional. Default: 100
  triggers:
    - type: rabbitmq
      metadata:
        queueName: create-erc-725-profile
        queueLength: "2"
      authenticationRef:
        name: {{ include "relayer.fullname" . }}-trigger